### ISSUE TITLE
Tirar a possibilidade de cor amarela para os States 

### ISSUE THREAD

**Issue by lucasvieira123** [lotus-tool/lotus-tool#51]

**Comment by emersonclima** [comment]
permitir cores customizáveis significa retirar a marcação padrão por cores, já que o usuário pode marcar cores livremente qualquer estado pode ser amarelo e não fará mais sentido usar o amarelo como marcador de estado inicial... desnaturaliza o LTS e deixa a aplicação próxima a um editor de grafo genérico...
